[package]
name = "roaring-bench"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]

[features]
quick = []

[dependencies]
croaring = "0.5.0"
error-chain = "0.7.2"
lazy_static = "1.4.0"
roaring = "0.7.0"
zip = "0.5.13"
